services:
  trainer:
    image: kenzodtu/mlops-group-20-trainer:latest
    container_name: mlops-trainer
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./wandb:/app/wandb
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_ENTITY=${WANDB_ENTITY}
      - WANDB_PROJECT=${WANDB_PROJECT}
    stdin_open: true
    tty: true

  api:
    image: kenzodtu/mlops-api:latest
    container_name: mlops-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./data/splits:/app/data/splits:ro
    depends_on:
      - trainer

networks:
  default:
    driver: bridge
