services:
  trainer:
    platform: linux/amd64
    image: kenzodtu/mlops-group-20-trainer:latest
    container_name: mlops-trainer
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
      - ./wandb:/app/wandb
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - WANDB_ENTITY=${WANDB_ENTITY}
      - WANDB_PROJECT=${WANDB_PROJECT}
    stdin_open: true
    tty: true
    networks:
      - mlops-network

  api:
    image: francescoorma/mlops-api:latest
    container_name: mlops-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./data/splits:/app/data/splits:ro
    networks:
      - mlops-network
    depends_on:
      - trainer

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: mlops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - mlops-network
    depends_on:
      - api

networks:
  mlops-network:
    driver: bridge