# configs/config.yaml
defaults:
  - model: default
  - training: default
  - _self_

paths:
  raw_path: "data/raw/language_detection.csv"
  processed_dir: "data/processed/"
  splits_dir: "data/splits/"
  model_save_path: "models/best_model.pt"

  api:
  host: "0.0.0.0"
  port: 8000