name: Data change triggering

on:
  push:
    branches: [main, Raulito]
    paths:
      - "scripts/download_data.sh"
  pull_request:
    branches: [main, Raulito]
    paths:
      - "scripts/download_data.sh"

jobs:
  run_data_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install dependencies
        run: |
          pip install .
          pip list

      - name: Download data
        run: |
          bash scripts/download_data.sh
