name: Model changes workflow

on:
  push:
    paths:
      - "models/**"                  # saved weights / artifacts
      - "mlops_group_20/model.py"    # model definition code
  pull_request:
    paths:
      - "models/**"
      - "mlops_group_20/model.py"

jobs:
  run_data_checker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup uv + Python
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.12"
          enable-cache: true

      - name: Install dependencies
        run: |
          uv sync
          pip list

      # Minimal trial to check if the model code runs
      - name: Small test model
        run: |
          uv run python -c "from mlops_group_20.model import LanguageClassifier; LanguageClassifier(vocab_size=1000, num_classes=17)"
